/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vianna.com.br.View;

import Vianna.com.br.DAOO.impl.AgendamentoDAO;
import Vianna.com.br.Model.Agendamento;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author wendel
 */
public class Agenda extends javax.swing.JFrame {

    /**
     * Creates new form Agenda
     */
    public Agenda() {
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAgendamento = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonAterar = new javax.swing.JButton();
        jButtonApagar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Textserch = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabelFundoPainel = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));

        jTableAgendamento.setBackground(new java.awt.Color(255, 255, 255));
        jTableAgendamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Cliente", "Serviço", "Valor", "Data", "Hora", "Observação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableAgendamento);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, 1020, 300));

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("X");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 10, 40, 30));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Pesquisa:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 80, 20));

        jButtonAterar.setBackground(new java.awt.Color(0, 153, 0));
        jButtonAterar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonAterar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAterar.setText("Alterar");
        jButtonAterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAterarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 283, 120, 30));

        jButtonApagar.setBackground(new java.awt.Color(255, 0, 51));
        jButtonApagar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonApagar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonApagar.setText("Apagar");
        jButtonApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApagarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonApagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 283, 130, 30));

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 280, 150, 30));

        Textserch.setBackground(new java.awt.Color(102, 102, 102));
        Textserch.setForeground(new java.awt.Color(255, 255, 255));
        Textserch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextserchActionPerformed(evt);
            }
        });
        getContentPane().add(Textserch, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 260, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setName("Pesquisa"); // NOI18N
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 1080, 130));

        jLabelFundoPainel.setBackground(new java.awt.Color(93, 111, 124));
        jLabelFundoPainel.setIcon(new javax.swing.ImageIcon("C:\\Users\\wendel\\Documents\\Projetos\\Daves\\BarberShop\\trabalhobarbearia\\src\\main\\java\\Vianna\\com\\br\\View\\Imagens\\Agenda-PainelFundo.png")); // NOI18N
        getContentPane().add(jLabelFundoPainel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 20, 1270, 940));

        jLabelFundo.setBackground(new java.awt.Color(66, 100, 123));
        jLabelFundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\wendel\\Documents\\Projetos\\Daves\\BarberShop\\trabalhobarbearia\\src\\main\\java\\Vianna\\com\\br\\View\\Imagens\\AgendaFundo.png")); // NOI18N
        getContentPane().add(jLabelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, -20, 1360, 1010));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            allAgenda = new AgendamentoDAO().buscarTodos();
            System.out.println(allAgenda);
        } catch (ClassNotFoundException ex) {
           JOptionPane.showMessageDialog(null, "Não foi possivel encontrar os agendamentos");
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(null, "Não foi possivel encontrar os agendamentos" );
        }
        
        preencheTable(allAgenda);
    }//GEN-LAST:event_formWindowOpened

    private void TextserchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextserchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextserchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ArrayList<Agendamento> allAgenda = null;
        try { 
            allAgenda = new AgendamentoDAO().buscarPorNome(Textserch.getText());
            preencheTable(allAgenda);
            
        } catch (ClassNotFoundException | SQLException ex) {
                JOptionPane.showMessageDialog(null, "Não foi possivel encontrar o nome " + ex);
                formWindowOpened(null);
        }
        
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagarActionPerformed
        int row= jTableAgendamento.getSelectedRow();
        DefaultTableModel model = new DefaultTableModel();
        if(row <= -1){
            model.removeRow(row);
            
        }else{
            
            
            if(JOptionPane.showConfirmDialog(null,
                    "Apagar o agendamento do cliente "+ allAgenda.get(row).getCliente().getNome()+"?",
                    "Deseja apagar o agendamento  ?",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                
                try {
                    new AgendamentoDAO().apagar(allAgenda.get(row).getId());
                } catch (ClassNotFoundException |SQLException ex) {
                      JOptionPane.showMessageDialog(null, "Não foi possivel apagar o agendamento ");
                } 
                JOptionPane.showMessageDialog(null, "apagou");
            }
            
        }
         formWindowOpened(null);
    }//GEN-LAST:event_jButtonApagarActionPerformed

    private void jButtonAterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAterarActionPerformed
        int row= jTableAgendamento.getSelectedRow();

        if(row <= -1){
        JOptionPane.showMessageDialog(null, "Selecione um Cliente");

            
        }else{
          AgendarServico det=  new AgendarServico();
          
          det.preparerEdit(allAgenda.get(row));
          det.setVisible(true);
          formWindowOpened(null);
           
        }
         
    }//GEN-LAST:event_jButtonAterarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agenda().setVisible(true);
              
            }
        });
    }
        private ArrayList<Agendamento> allAgenda;

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Textserch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonApagar;
    private javax.swing.JButton jButtonAterar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelFundoPainel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableAgendamento;
    // End of variables declaration//GEN-END:variables

    private void preencheTable(ArrayList<Agendamento> allAgenda) {
        //(int id, Cliente cliente,Servico servico,  double valor, String data,String hora,String observacao)
        DefaultTableModel dftm = (DefaultTableModel) jTableAgendamento.getModel();
            while(dftm.getRowCount() >0){
                dftm.removeRow(0);
            }
        for(Agendamento  age: allAgenda){
            String[] linha = {age.getId()+"",age.getCliente().getNome()+"",age.getServico().getDescricao()+"",age.getValor()+"",age.getData()+"",
                age.getHora()+"",age.getObservacao()+""};
            dftm.addRow(linha);
        }
        
    }

    
}
