/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vianna.com.br.View;


import Vianna.com.br.Controller.Helper.LoginController;
import Vianna.com.br.DAOO.impl.UsuarioDAO;
import Vianna.com.br.Model.Usuario;
import Vianna.com.br.View.Cadastrar;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author wendel
 */
public class Login extends javax.swing.JFrame {

    private final LoginController controller;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        controller =new LoginController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextSenha = new javax.swing.JPasswordField();
        TextUsuario = new javax.swing.JTextField();
        jButtonEntrar = new javax.swing.JButton();
        jButtonEntrar1 = new javax.swing.JButton();
        jButtonCadastrar = new javax.swing.JButton();
        jLabelUsuario1 = new javax.swing.JLabel();
        jLabelSenha = new javax.swing.JLabel();
        jLabelCadastrar = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextSenha.setBackground(new java.awt.Color(51, 51, 51));
        TextSenha.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(TextSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 370, 30));

        TextUsuario.setBackground(new java.awt.Color(51, 51, 51));
        TextUsuario.setForeground(new java.awt.Color(255, 255, 255));
        TextUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(TextUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 360, 30));

        jButtonEntrar.setBackground(new java.awt.Color(255, 51, 51));
        jButtonEntrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonEntrar.setForeground(new java.awt.Color(51, 51, 51));
        jButtonEntrar.setText("Sair");
        jButtonEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnSair(evt);
            }
        });
        getContentPane().add(jButtonEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, 160, 30));

        jButtonEntrar1.setBackground(new java.awt.Color(51, 153, 255));
        jButtonEntrar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonEntrar1.setForeground(new java.awt.Color(51, 51, 51));
        jButtonEntrar1.setText("Login");
        jButtonEntrar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonEntrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrar1JBtnLogar(evt);
            }
        });
        getContentPane().add(jButtonEntrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, 190, 40));

        jButtonCadastrar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButtonCadastrar.setText("Cadastarar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 570, -1, -1));

        jLabelUsuario1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelUsuario1.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabelUsuario1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsuario1.setText("Usuario");
        getContentPane().add(jLabelUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 221, 70, 40));

        jLabelSenha.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSenha.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabelSenha.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSenha.setText("Senha");
        getContentPane().add(jLabelSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 321, 80, 40));

        jLabelCadastrar.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCadastrar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelCadastrar.setForeground(new java.awt.Color(204, 204, 204));
        jLabelCadastrar.setText("Não possui uma senha ?");
        getContentPane().add(jLabelCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 570, 250, 20));

        jLabelUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jLabelUsuario.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabelUsuario.setText("Usuario");
        getContentPane().add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 221, 70, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\wendel\\Documents\\Projetos\\Daves\\BarberShop\\trabalhobarbearia\\src\\main\\java\\Vianna\\com\\br\\View\\Imagens\\painel-login.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 580, 520));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\wendel\\Documents\\Projetos\\Daves\\BarberShop\\trabalhobarbearia\\src\\main\\java\\Vianna\\com\\br\\View\\Imagens\\Logo.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 770));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TextUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextUsuarioActionPerformed

    private void JBtnSair(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnSair
        System.exit(0);
    
    }//GEN-LAST:event_JBtnSair

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        new Cadastrar().setVisible(true);

    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jButtonEntrar1JBtnLogar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrar1JBtnLogar
        try {
            Usuario u= new UsuarioDAO().buscarLoginSenha(TextUsuario.getText(),TextSenha.getText());
            
            if(u == null){
                JOptionPane.showMessageDialog(null,"nome ou senha incorreta");
                TextUsuario.setText("");
                TextSenha.setText("");
                TextUsuario.requestFocus();
            }else{
                setVisible(false);
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Não foi possivel encontrar o Usuario.");
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }//GEN-LAST:event_jButtonEntrar1JBtnLogar

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField TextSenha;
    private javax.swing.JTextField TextUsuario;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JButton jButtonEntrar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCadastrar;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JLabel jLabelUsuario1;
    // End of variables declaration//GEN-END:variables

    public void exibeMensagem(String mensagem) {
    JOptionPane.showMessageDialog(null,mensagem);
    }
    public void entarSistema( ) {
    
        
    }

    public JPasswordField getTextSenha() {
        return TextSenha;
    }

    public void setTextSenha(JPasswordField TextSenha) {
        this.TextSenha = TextSenha;
    }

    public JTextField getTextUsuario() {
        return TextUsuario;
    }

    public void setTextUsuario(JTextField TextUsuario) {
        this.TextUsuario = TextUsuario;
    }
    
}
